### ISSUE TITLE
count(): Parameter must be an array or an object

### ISSUE THREAD

**Issue by jbyvosges** [craigk5n/webcalendar#103]
count(): Parameter must be an array or an object that implements Countable in
includes/functions.php on line 2929
Warning: count(): Parameter must be an array or an object that implements Countable in /includes/menu/index.php on line 134
Warning: A non-numeric value encountered in /edit_entry.php on line 453

```
PROGRAM_NAME: WebCalendar v1.2.7 (22 Feb 2013)
SERVER_SOFTWARE: Apache/2.4.29 (Ubuntu)
Web Browser:Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0
PHP Version: 7.2.7-0ubuntu0.18.04.2
Default Encoding:UTF-8
db_type:mysqli
```

**Comment by craigk5n** [comment]
The menu/index.php was fixed recently with a separate issue.  The functions.php issue was also fixed.  Try out the latest code to verify, but I'm assuming this has been fixed.
