### ISSUE TITLE
Reminders Not Sent

### ISSUE THREAD

**Issue by Riskier4ra** [craigk5n/webcalendar#104]
Hi, I am new to WC and just installed the latest version.   The only issue I see so far is that reminders are not being sent.  Anyone know why or what I can do to resolve it?   Thanks -

**Comment by bbannon** [comment]
1) you have to set up a CRON job outside of WebCalendar.
2) my ISP no longer allows CRON jobs.

You may be able to set up a CRON with an independent company.
Try cron-job.org for a free account.

**Comment by Riskier4ra** [comment]
I can setup CRON with my hosting company.  Can you tell me what I need to do to make this happen?

**Comment by bbannon** [comment]
My computer died so, I don't have access to the docs right now. 
There should be some fairly detailed instructions in the administrator guide.

**Comment by craigk5n** [comment]
Check out the docs on the WebCalendar home page:

http://k5n.us/wp/webcalendar/#Documentation

In particular the Sys Admin Guide has a section on setting up reminders:

https://htmlpreview.github.io/?https://github.com/craigk5n/webcalendar/blob/master/docs/WebCalendar-SysAdmin.html#reminders
