### ISSUE TITLE
Custom Header, Trailer or Script - Getting Fatal Error

### ISSUE THREAD

**Issue by oldhatt45** [craigk5n/webcalendar#110]
I'm having a problem trying to figure out what's wrong with these 3 pieces of code that I'm trying to add to the Custom Header, Trailer and Script settings in System Preferences.
They worked in the 1.2 version of Webcalendar but in 1.3 I'm getting a Fatal Error when trying to add the code.

Would really appreciate some help with this.

Thanks In Advance

Charlie

Custom Header for Webcalendar
===============================

<div id="masthead"> 
  <h1 id="siteName"><img name="Logo" src="../images/banner.png" width="100%" height="167" alt="Dog Club"></h1> 
  <div id="globalNav"> 
    <a href="../index.php">Home</a> | <a href="../Join.php">Join </a> | <a href="../Progs.php">Obedience & Pet Training</a> | 
	<a href="../ClassSched.htm">Class Schedules</a> | <a href="../Contacts.php">Contacts</a> | <a href="../Directions.php">Directions</a> | <a href="../AboutUs.htm">About Us</a>
  </div> 
</div>
<table width="100%"  border="0" cellpadding="0">
<tr>
<td width=25% valign="top">
<div id="navBar2"> 
  <div id="search"> 
    <form action="#"> 
      <label>Search </label> 
      <input name="searchFor" type="text" size="22"> 
      <input name="goButton" type="submit" value="go"> 
    </form> 
  </div> 
  <div id="sectionLinks"> 
    <h3 align="left">Menu</h3> 
	<table width="100%"  border="0" cellpadding="1">
	  <tr> 
		<td><script type='text/javascript'> function Go(){return}</script> 
			<div id='MenuPos' style='position:relative; width:200; height:200;'><img src='../images/transparent.gif' width='200' height='200'></div></td>
	  </tr>
	</table>
	<script type='text/javascript' src='../menu_var2.js'></script>
	<script type='text/javascript' src='../menu_com.js'></script>
	<noscript>
	<p>&nbsp;</p>
	<p>&nbsp;</p>
	<p>Your browser does not support script</p>
	</noscript>
  </div> 
  <div class="relatedLinks"> 
    <h3>&nbsp;</h3> 
  </div>
  <div class="relatedLinks"> 
    <h3>&nbsp;</h3> 
  </div>
</div> 
</td>
<td width="75%>
<div id="content"> 

==================
Custom Trailer for Webclaendar
====================
</div> 
</td>
</tr>
</table>
<div id="siteInfo"> 
  <div align="center">
    <p><a href="#">About Us</a> | <a href="#">Site
      Map</a> | <a href="#">Privacy Policy</a> | <a href="#">Contact Us</a> </p>
  </div>
</div> 

============================
Custom Script for Webcalendar
============================
<?php
require_once('../config.php');
access_control();
if (isset($_SESSION['ShowMOMenu'])) {
	if ($_SESSION['ShowMOMenu'] == 1 || $_SESSION['ShowMOMenu'] == "1" ) {
		$ShowMOMenu = 1;
	} else {
		$ShowMOMenu = 0;
	}
} else {
	$ShowMOMenu = 0;
	$_SESSION['ShowMOMenu'] = 0;
}
?>
<script language="javascript">
ShowMemMenu = "<?php echo $_SESSION['ShowMOMenu']; ?>";
ShowMemRole = "<?php if(isset($_SESSION['user_roles_string'])) {echo $_SESSION['user_roles_string']; } else { echo 0; } ?>";
ShowMemRoleCount = "<?php if(isset($_SESSION['user_roles'])) { echo count($_SESSION['user_roles']); } else { echo 0; } ?>";
</script><link rel="stylesheet" href="../2col_leftNav.css" type="text/css">

========================================

**Comment by oldhatt45** [comment]
Sorry the original post is messed up.
Will try to add the code differently. 
This isn't my day.  :(

**Comment by craigk5n** [comment]
Yeah, I'll need more info to help you out here.  Is the fatal error generated from WebCalendar?  Or Apache?  Or the browser?
