### ISSUE TITLE
Parse error: syntax error, unexpected '[' in ... includes/init.php on line 360

### ISSUE THREAD

**Issue by yurivict** [craigk5n/webcalendar#121]
```
Parse error: syntax error, unexpected '[' in /home/xx61/public_html/webcalendar-new-d00f980/includes/init.php on line 360
```
rev.d00f980

**Comment by FranzGotsis** [comment]
See issue #113. 
This is most likely a problem with an older release of WebCalendar (1.2.7 or older) with PHP Version 7.x.
Install 1.2.9 or the development branch which runs fine on PHP 7.x.

In case you report an error or a problem, please add additional information:
1) Version of WebCalendar, 
2) Name of database and release
3) PHP-Version
4) a description of what happened exactly: 
    Did you install from scratch (downloading from github or via a menu provided 
    from your hosting company).
    Did WebCalendar run before? In that case describe the change that led to the problem.

**Comment by craigk5n** [comment]
This should be fixed in the latest code.

Thanks for the assistance Franz 👍
