### ISSUE TITLE
Issue accessing admin panel after installation

### ISSUE THREAD

**Issue by codingmona** [craigk5n/webcalendar#132]
Hello,

I have just finished installing the project and when I try to login to the admin panel using the default admin access I get the error below:
Notice: crypt(): No salt parameter was specified. You must use a randomly generated salt and a strong hash function to produce a secure hash. in login.php
 Warning: Cannot modify header information - headers already sent by login.php

Thanks!

**Comment by FranzGotsis** [comment]
To be able to help you need to provide more information:
What release of WebCalendar are you using?
On what system (e.g. linux distribution) are you running WebCalendar?
What PHP version are you using?
kind regards
Franz Gotsis, Munich

**Comment by JBFelizberto** [comment]
I have the same error:
What release of WebCalendar are you using? the lasted - downloaded on 07/06
On what system (e.g. linux distribution) are you running WebCalendar? windows server 2012
What PHP version are you using? 7.2.10

JB

**Comment by EverBS2014** [comment]
I have the same error since I changed from PHP 5.3 to 7.3 I also use the calendar 1.3.0

**Comment by chrismyers81** [comment]
Same here, PHP 7.3 on Debian Buster.

**Comment by craigk5n** [comment]
Should be fixed with commit e6e33f52b10edeaf9f77ffb6856c50035e9514f2.

**Comment by chrismyers81** [comment]
Thank you! I don't get that error anymore.
