### ISSUE TITLE
Can't Login to Admin account – PHP Fatal error – PHP 7.2

### ISSUE THREAD

**Issue by niemalsnever** [craigk5n/webcalendar#133]
Hello,
we're testing WebCalender 1.2.9 on PHP 7.2-fpm, in order to get rid of PHP 5.x on our web servers. So we recently cloned our old 1.2.7 database, and setup a new instance of WebCalendar 1.2.9 on our test server running:
- Ubuntu 18.04.2 LTS
- Apache/2.4.29
- PHP 7.2.15-0ubuntu0.18.04.1 (fpm-fcgi)

We're running into a major issue when trying to login, using the builtin authentication scheme:

> Warning: count(): Parameter must be an array or an object that implements Countable in /var/www/vhost.example.com/includes/menu/index.php on line 131
>
> Fatal error: Uncaught Error: [] operator not supported for strings in /var/www/vhost.example.com/includes/menu/index.php:240 Stack trace: #0 /var/www/vhost.example.com/includes/init.php(154): include_once() #1 /var/www/vhost.example.com/month.php(95): print_header(Array, '<script src="in...', NULL, false, false, false, false) #2 {main} thrown in /var/www/vhost.example.com/includes/menu/index.php on line 240

If you have further questions, don't hesitate to contact me.

Best Regards
niemalsnever

**Comment by craigk5n** [comment]
Hopefully fixed with commit bf4eaa44c8c1a0e30701227d409c8d35a65aad82
