### ISSUE TITLE
edit_entry_handler outputs communication with SMTP server

### ISSUE THREAD

**Issue by tbesand** [craigk5n/webcalendar#134]
Hi everybody,

I've setup a new installation of webcalendar 1.30.
Had some difficulties setting up the mail functionality, but it's sending mails, now.
The problem is, that when invoking edit_entry_handler (clicking on save event), the script will output the complete communication/handshake between webcalendar and the SMTP server.
Please see attached screenshot.
I've tested with all available "Email Mailer" settings: "sendmail", "PHP mail", and "SMTP", same result.

Anyone knows the problem? How can I get rid of this unwanted behaviour?

Thanks beforehand!
Cheers, /T
![screenshot](https://user-images.githubusercontent.com/48181567/53697151-aad2a680-3dce-11e9-9a72-47a5abf4fd8a.png)

**Comment by craigk5n** [comment]
Fixed with recent pull request and commit 2ad7c2121e5afaf9a8086c63fdb5a1b1e74a4522
