### ISSUE TITLE
WebCalendar v1.3.0: Some important files in "includes" directory are missing in release

### ISSUE THREAD

**Issue by codifex** [craigk5n/webcalendar#138]
In the v1.3.0 release zip and tar.gz some files and directories seem to be missing, e.g., in the includes/js directory.  As a consequence, essential functionality of the calendar such as adding new appointments via double-clicking does not work.  These files and directories are available in the master branch.

**Comment by craigk5n** [comment]
Should be included in updated release tar.gz/zip posted today.

**Comment by codifex** [comment]
Fine, thanks a lot :-)!
