### ISSUE TITLE
Add new event using + sign on phone and tablets. 

### ISSUE THREAD

**Issue by blueskies76** [craigk5n/webcalendar#152]
In previous versions, we can easily add new events using   "+" button in the upper right corner of each day in the monthly calendar view. Otherwise, it is very hard to add new event on phone and tablets. I would support adding this feature.

**Comment by janvanl** [comment]
We have the same, it is harder to add a new event on a phone now, the double-click does not work on phones.

**Comment by adam12b1** [comment]
Note that there is a setting, stored as `ADD_LINK_IN_VIEWS` in the `webcal_config` database table, that is supposed to bring back the `+` links and would thus solve this issue, but it appears to be broken. Just filed bug https://github.com/craigk5n/webcalendar/issues/220.

**Comment by craigk5n** [comment]
Duplicate issue
