### ISSUE TITLE
Parse error: syntax error, unexpected '[' in ... includes/init.php on line 360

### ISSUE THREAD

**Issue by tonywilson** [craigk5n/webcalendar#156]
A similar issue (#121) was raised on this issue, but our problem seems to be slightly different.  We're upgrading from Webcalendar 1.2.7 to 1.3.0 and are experiencing some issues.  Our server is running PHP version 5.3.9, which appears not to support the array initialization construct [ ] (https://stackoverflow.com/questions/40624805/parse-error-syntax-error-unexpected-how-to-fix-this-one).  I've been unable to find any indication of a minimum PHP requirement for WebCalendar.  Is the older PHP version the source of our problem, and if so, is there a workaround other than upgrading the PHP package?  Webcalendar is running on a group server, and the admin is reluctant to update PHP without a good reason due to potential compatibility issues for other users.

**Comment by codifex** [comment]
WebCalendar 1.3.0 requires PHP 7.1 or newer according to https://github.com/craigk5n/webcalendar/commit/7efab1173eefbbb59466d94c2344464ee70b4471

**Comment by craigk5n** [comment]
Yes, PHP 7 is required for WebCalendar 1.3 as listed in the [System Requirements](http://k5n.us/wp/webcalendar/#System_Requirements).

PHP 5 is no longer being supported (no new releases) as described [here](https://www.php.net/supported-versions.php).
