### ISSUE TITLE
The Sqlite3 populating script is broken

### ISSUE THREAD

**Issue by bodqhrohro** [craigk5n/webcalendar#157]
It fails with `PHP Fatal error:  Uncaught ArgumentCountError: SQLite3::__construct() expects at least 1 parameter, 0 given in <..>/webcalendar/install/sql/tables-sqlite3.php:7` error.

The whole code in [that module](https://github.com/craigk5n/webcalendar/blob/master/install/sql/tables-sqlite3.php) is strange.   Looks like it was just recreated from something other without testing. The parameters of the constructor and the `query` method don't match the [documentation](https://www.php.net/manual/en/class.sqlite3.php) of the SQLite3 module.

And I couldn't understand the purpose of opening a new database connection when there is already a database handle passed in the argument, so I just [patched](https://github.com/bodqhrohro/webcalendar/commit/568699452ca10473dbfde09f2958e8824d762bc8) the code to use that handle instead. But I'm not sure if this is enough; what was `$c` intended for? Maybe it was supposed to be a workaround to use the `query` method in a static way, or an attempt to cover the case when the handle is not provided?

**Comment by craigk5n** [comment]
Resolved with PR from your fork.  Thanks :-)
