### ISSUE TITLE
PHP Problem in /includes/js/edit_entry.php

### ISSUE THREAD

**Issue by janvanl** [craigk5n/webcalendar#161]
Hi,

I have E-Mail active with SMTP and a server/account that is testet and functional.

When adding an event Webcal breaks with the following PHP error

[Tue Aug 13 17:43:28.872389 2019] [fcgid:warn] [pid 11079] [client 212.89.175.135:47282] mod_fcgid: stderr: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/..../includes/js/edit_entry.php on line 180, referer: https://..../edit_entry.php?date=20190814&defusers=

It concerns the function addGroup()
on line 180 is
`for ( $i = 0; $i < count ( $groups )  ; $i++ ) {`

Seems that the problem is here
$groups = get_groups ( $user );
look like $groups should have been an array
but I am not a programmer!

PHP is version 7.1.31

Regards,
Jan

**Comment by craigk5n** [comment]
Fixed in main branch.
