### ISSUE TITLE
probable solution for touchscreens

### ISSUE THREAD

**Issue by janvanl** [craigk5n/webcalendar#163]
Hi,
I found
https://www.jqueryscript.net/other/jQuery-Plugin-For-Double-Click-Tap-Detection-doubleTap.html

You use dblclick_add.js

I will try if it helps changing to the jquery plugin.

Regards,
Jan

**Comment by janvanl** [comment]
Hi,

I have placed a + (plussign) as a link again.

in includes/functions.php
at about line 4606

just after 
substr ( $date, 6, 2 ) . '</a>
add
<span style="float:right"><a href="edit_entry.php?date='.$date.'" title="Einzelklick fügt einen neuen Termin ein."><b><u>[&nbsp;+&nbsp;]</u></b></a>&nbsp;&nbsp;&nbsp;&nbsp;</span> 

In the month-view you will see a link [ + ] if you click or tap on it a new entry can be made.

Regards,
Jan

**Comment by john-mcdermott** [comment]
Hello Jan. Would you mind providing a bit more detail on this. I have added the code as you directed but it just ends up stop the webcalendar from loading.

This is where I have placed your code as instructed...

substr ( $date, 6, 2 ) . '</a>'<span style="float:right"><a href="edit_entry.php?date='.$date.'" title="Einzelklick fügt einen neuen Termin ein."><b><u>[&nbsp;+&nbsp;]</u></b></a>&nbsp;&nbsp;&nbsp;&nbsp;</span> .  ( empty ( $tmp )
      ? '' : '<img src="images/' . $tmp . 'moon.gif" title="' . $moon_title
      . '" alt="' . $moon_title . '" />' ) . "<br />\n";

Have I done something wrong? With the addition of the code again the webcal simply doesn't load...

Any help is very much appreciated!!! Much Thanks, John

**Comment by janvanl** [comment]
I will copy a bigger part of the code.
Must look up where I have it.

**Comment by janvanl** [comment]
Hi,
this is the code from line 4592 to 4610. 


```
 if ( ! $ssi ) {
  /* translate ( 'First Quarter Moon') translate ( 'Full Moon' )
     translate ( 'Last Quarter Moon') translate ( 'New Moon' )
   */
    $userCatStr = ( strcmp ( $user, $login ) ? 'user=' . $user . '&amp;' : '' )
     . ( empty ( $cat_id ) ? '' : 'cat_id=' . $cat_id . '&amp;' );
    $tmp = ( empty( $moons[$date] ) ? '' : $moons[$date] );
    $moon_title = ( empty ( $tmp ) ? '' : translate ( ucfirst ( $tmp )
     . ( strpos ( 'fullnew', $tmp ) !== false ? '' : ' Quarter' ) . ' Moon' ) );
    $ret = ( $can_add ? '
        <a title="' . $newEntryStr . '" href="edit_entry.php?' . $userCatStr
       . 'date=' . $date . '"><img src="images/new.gif" alt="' . $newEntryStr
       . '" class="new" /></a>' : '' ) . '
        <a class="dayofmonth" href="day.php?' . $userCatStr . 'date=' . $date
     . '">' . substr ( $date, 6, 2 ) . '</a><span style="float:right"><a href="edit_entry.php?date='.$date.'" title="Einzelklick fügt einen neuen Termin ein."><b><u>[&nbsp;+&nbsp;]</u></b></a>&nbsp;&nbsp;&nbsp;&nbsp;</span>' . ( empty ( $tmp )
      ? '' : '<img src="images/' . $tmp . 'moon.gif" title="' . $moon_title
      . '" alt="' . $moon_title . '" />' ) . "<br />\n";
    $cnt++;
  }
```
It is working in my calendar and that of the customer.
Mind the quotes. Seems you made a mistake there.

Regards,
Jan

**Comment by john-mcdermott** [comment]
Jan this is so very much appreciated...!!!

 

Thank you, John

 
 

Sent: Thursday, February 27, 2020 at 12:50 AM

**Comment by john-mcdermott** [comment]
Got it to work on a fresh 1.3 install. So can confirm that. 

 

Unfortunately, it does not appear to work with a cpanel updated install from 1.29->1.3. No idea why.

 

Again appreciated in any case!!!

 

Thank you Jan

 

Cheers, John

 
 

Sent: Thursday, February 27, 2020 at 12:50 AM

**Comment by adam12b1** [comment]
Note that there is a setting, stored as `ADD_LINK_IN_VIEWS` in the `webcal_config` database table, that is supposed to bring back the `+` links and would thus solve this issue within Webcalendar, but it appears to be broken. Just filed bug https://github.com/craigk5n/webcalendar/issues/220.
