### ISSUE TITLE
Cannot install with PHP 7.x because (get|set)_magic_quotes_runtime had been removed

### ISSUE THREAD

**Issue by lkppo** [craigk5n/webcalendar#168]
Hello,

I can't install webcalendar because the setup process use (get|set)_magic_quotes_runtime which had been removed since PHP 7.0.

Regards,

**Comment by lkppo** [comment]
One error:


( ! )  Fatal error: Uncaught Error: Call to undefined function  set_magic_quotes_runtime() in  C:\WinNMP\WWW\webcalendar\install\index.php on line 114
--



1 | 0.0000 | 631272 | {main}(  ) | ...\index.php:0

**Comment by ziegel** [comment]
Fix described @ https://sourceforge.net/p/webcalendar/discussion/11588/thread/56a786bd/
Tested and worked fine for me. (using PHP 7.3.3) Sugggest to close this issue.
