### ISSUE TITLE
Cannot install with PHP 7.x because preg_replace is used with /e modifier

### ISSUE THREAD

**Issue by lkppo** [craigk5n/webcalendar#169]
Hello,

I cannot install webcalendar with PHP 7.x because preg_replace is used with /e modifier which is deprecated since PHP 7.0.

One error during the setup process:

( ! )  Warning: preg_replace(): The /e modifier is no longer supported, use  preg_replace_callback instead in  C:\WinNMP\WWW\webcalendar\includes\formvars.php on line 48
--
1 | 0.0040 | 631344 | {main}(  ) | ...\index.php:0
2 | 0.6230 | 1334400 | getGetValue(  ) | ...\index.php:162
3 | 0.6230 | 1334400 | preventHacking(  ) | ...\formvars.php:106
4 | 0.6230 | 1334400 | preg_replace (  ) | ...\formvars.php:48

Regards,

**Comment by craigk5n** [comment]
Which version are you using?  I think this may be out of date compared to what is in the latest git.  If it's still re-open
