### ISSUE TITLE
In install script that are calls to mysql driver which is incompatible with PHP 7.x

### ISSUE THREAD

**Issue by lkppo** [craigk5n/webcalendar#172]
In install script that are calls to mysql driver which is incompatible with PHP 7.x

**Comment by craigk5n** [comment]
I need more details about what the issue is.  What call is failing?  Is it the mysql or mysqli interface?  Please re-open the issue with the extra details.

I just tried PHP 7.4 and MySQL with the new docker setup recently added, and it worked fine for me... So, I was unable to reproduce this.

**Comment by lkppo** [comment]
I use mysqli. Anyway, mysql support has been removed in favor of mysqli since PHP 7.0.

See https://www.php.net/manual/en/changelog.mysql.php

settings.php:

```
<?php
/* updated via install/index.php on Wed, 20 Jan 2021 14:03:25 -0500
install_password: 81dc9bdb52d04dc20036dbd8313ed055
db_cachedir: /tmp
db_host: localhost
db_login: root
db_persistent: false
db_type: mysqli
readonly: false
single_user: false
use_http_auth: false
user_inc: user.php
db_database: webcalendar
# end settings.php */
?>
```

![connection_error_mysqli](https://user-images.githubusercontent.com/10128284/105222783-3ee0bf00-5b5b-11eb-807b-7669e79842cd.png)
