### ISSUE TITLE
Calendar not working -HTTP ERROR 500

### ISSUE THREAD

**Issue by lawresolve** [craigk5n/webcalendar#174]
Hi,
I have lost access to my calendar. When I attempt to go to the webpage, I get the following error:

This page isn’t working
lawresolve.net is currently unable to handle this request.
HTTP ERROR 500

Do you have any suggestions on how to fix this issue ?

Thanks!

**Comment by bbannon** [comment]
I've had the same problem. My ISP had made some "security patches" without telling anyone. Ask them what they did. If you can tell us what they say, maybe someone here can make a fix.

**Comment by craigk5n** [comment]
Sounds like an ISP issue.  Without knowing what the actual server error is (usually in the HTTP error log), there's no real way to address this, so I'm closing this for now.  If are able to get details about the error, feel free to post those and re-open the issue.
