### ISSUE TITLE
Does not run under PHP 7.2

### ISSUE THREAD

**Issue by gewahl** [craigk5n/webcalendar#175]
Effective December my provider will stop support for PHP versions up to 7.1, so I changed to 7.2.
Even with v1.3.0, I get error messages like

> Deprecated: assert(): Calling assert() with a string argument is deprecated in path/includes/access.php on line 354 (and 314)
> Warning: Cannot modify header information - headers already sent by (output started at path/includes/access.php:354 in path/includes/functions.php...

Can I expect a fix before PHP 7.1 will be cut off?

**Comment by gonzagentil** [comment]
Hi, Do you have any advance?  I´m stucked in the same.
thks in advance.

**Comment by gewahl** [comment]
I was told that assert() should not have been used in a productive environment at all, only for testing...
This is what I found out to keep WebCal running:
You can comment out all lines with that function, which can be found in a couple of files. 
However, a much more elegant solution is to add "zend.assertions = -1" to your php.ini instead.

**Comment by craigk5n** [comment]
Should be resolved with commnit 412be585cf059173a3d5312a3018a1391e2f3ba1.  Re-open this issue if you find this did not resolve your issue.
