### ISSUE TITLE
Remote publishing /icalclient.php to Thunderbird Lightning calendar?

### ISSUE THREAD

**Issue by Collum101** [craigk5n/webcalendar#177]
Trying to bring my WebCalendar into lightning calendar in thunderbird mail.

Allows me to create the calendar in lighting however does not accept my user login for WebCalendar to authenticate the connection.

Created the calendar in lightning via: create new calendar>on the network>remote calendar format: iCalendar (ICS) and pasted my allow remote publishing url in the location.

Please advise?

**Comment by craigk5n** [comment]
There was once a wiki page somewhere that documented how to set this up.  But the wiki software had to be retired (security issues), and some content was lost :-(

I added a new wiki page with instructions here:

https://github.com/craigk5n/webcalendar/wiki/Connecting-an-iCal-Client-(Thunderbird,-Apple-iCal)
