### ISSUE TITLE
Undefined variable "raw" in includes/functions.php

### ISSUE THREAD

**Issue by Doug-Peterson** [craigk5n/webcalendar#182]
This is for 1.3.0. The following showed up in the Apache error log.

PHP Notice:  Undefined variable: raw in [path removed]/webcalendar/includes/functions.php on line 4400, referer: [path removed]/webcalendar/day.php?date=20191011

4398      $GLOBALS[$prefix . 'lastname'] = $row[1];
4399      $GLOBALS[$prefix . 'firstname'] = $row[2];
4400      $GLOBALS[$prefix . 'fullname'] = trim($raw[1] . ' ' . $row[2]);

I would assume the "raw" in line 4400 should be "row" and that it would be safe to make the change myself.

**Comment by Doug-Peterson** [comment]
I change raw to row. WebCalendar seems to be working fine with no error.

**Comment by WhoHasMyUsername** [comment]
Thanks! I had this one, too:

<code>2020-02-05 10:29:26: (mod_fastcgi.c.421) FastCGI-stderr: PHP Notice:  Undefined index: MINICALFONT in WebCalendar-1.3.0/includes/css/styles.php on line 153</code>

I commented the missing index out in includes/css/styles.php, line 153:
<code>  --minicalfont: <?php #echo$GLOBALS['MINICALFONT']; ?>;</code>

Same voor MINICALWIDTH, NEXTMONTHBG, PREVMONTHBG.

**Comment by craigk5n** [comment]
Should be fixed in latest version in git
