### ISSUE TITLE
Undefined index for MINICALFONT, MINICALWIDTH,  NEXTMONTHBG and PREVMONTHBG

### ISSUE THREAD

**Issue by Doug-Peterson** [craigk5n/webcalendar#183]
This is for 1.3.0 running under PHP version 7.0.33-0+deb9u6. The following showed up in the Apache error log.

PHP Notice:  Undefined index: MINICALFONT in [path removed]/includes/css/styles.php on line 153, referer: [path removed]/webcalendar/day.php?date=20191011

PHP Notice:  Undefined index: MINICALWIDTH in [path removed]/includes/css/styles.php on line 154, referer: [path removed]/webcalendar/day.php?date=20191011

PHP Notice:  Undefined index: NEXTMONTHBG in [path removed]/includes/css/styles.php on line 156, referer: [path removed]/webcalendar/day.php?date=20191011

PHP Notice:  Undefined index: PREVMONTHBG in [path removed]/webcalendar/includes/css/styles.php on line 160, referer: [path removed]/webcalendar/month.php?year=2019&month=11

**Comment by Doug-Peterson** [comment]
After looking through code (not being particularly well versed in php) it seems like these globals settings may not have been fully implemented. I removed them from styles.php. WebCalendar seems to be working fine with no errors.

  --minicalfont: <?php echo$GLOBALS['MINICALFONT']; ?>;
  --minicalwidth: <?php echo$GLOBALS['MINICALWIDTH']; ?>;
  --nextmonthbg: <?php echo$GLOBALS['NEXTMONTHBG']; ?>;
  --prevmonthbg: <?php echo$GLOBALS['PREVMONTHBG']; ?>;

**Comment by wurtel2** [comment]
These apparently are meant for a "mini" calendar that is to be used e.g. in an iframe. I also removed them.

**Comment by craigk5n** [comment]
Fixed with commit a7360f9cea12915fa3612847b95e6ca412b0b0f4
