### ISSUE TITLE
2 installs 1.30 different file includes/functions.php

### ISSUE THREAD

**Issue by janvanl** [craigk5n/webcalendar#187]
Hi,

I have 2 installs, one is a production-site, the other a test-site.
Both have version 1.30 15th of march 2019

I adjusted the test-install, includes/functions.php line 4606 with a link that returns the possibility to open a new event like the image with the plussign in 1.27.
In production the file includes/functions.php is a few hundred lines smaller.
The adjustment does not work there.

What can I do to make the installs identical, can i just copy the newer files over the older ones?

Anyone have some insight in this?

YES I HAVE
I mixed up an old installation with a new one . . . 
It is working.

regards,
Jan

**Comment by craigk5n** [comment]
You would need to copy over all the files/dirs except for:

- includes/settings.php
- icons directory

If you grab a new 1.30 zip file, you should be able to unzip it ontop of the out-dated install.
