### ISSUE TITLE
CalDAV server support

### ISSUE THREAD

**Issue by krcook** [craigk5n/webcalendar#188]
Has any work been started to implement a CalDAV server within webCalendar?

I don't want to duplicated effort - so if not, i might be interested in adding this feature.

**Comment by craigk5n** [comment]
I am not aware of any ongoing development around WebDAV.

**Comment by krcook** [comment]
Is it a worthwhile feature that you would like to see implemented? - it looks like would allow webCalendar to be used with a lots of other clients such as Android Apps.
