### ISSUE TITLE
cal_create_by is me instead of boss when creating new event as assistant

### ISSUE THREAD

**Issue by pdivers** [craigk5n/webcalendar#189]
running version 1.30.  
expected behavior: I think 'created by' should be boss when event is created by an assistant
observed: 'created by' is always the assistant. I think this prevents other assistants (of this boss) that are not assistants of the assistant from editing the event. Also annoying that the 'default participant' is me and not 'boss'

I'm not 100% sure that this is a bug, maybe someone can point me to the file and line that determines what gets written to this field. I've taken pot shots at it but same results.

**Comment by pdivers** [comment]
Maybe this can be closed. I just discovered that if I add an event by clicking the top menu option <Events><Add New Event> instead of double-clicking a day to add, it works as expected and displays 
"Created by  'boss' ( by 'assistant' )" as I would expect.

**Comment by craigk5n** [comment]
The defusers URL parameter was not being properly handled in edit_entry.php.  Commit 4ae5d84cc00cfe1a15bfec407cba0cfa7d3b84de should fix this issue.
