### ISSUE TITLE
purge database function

### ISSUE THREAD

**Issue by pdivers** [craigk5n/webcalendar#191]
Is there an option somewhere that will purge past events from the database? My calendar is getting very slow and I think it might have to do with the fact that I have entries going back to 1999.
I started to delete entries using sql but then I realized that there are tendrils of those events in other tables that must also be removed.  
If table does not contribute to slow page loads then it must be a godaddy thing.

**Comment by craigk5n** [comment]
Yes, there is a purge function.  I don't believe there is a link to it in within the menu anymore.  Just go to purge.php on your webcalendar installation.

I have events going back to 20 years also and don't see a huge slowdown in performance.  Some if it may be an issue of resources (slow PC, etc.)   Do you have the db caching function setup?  (Check your `includes/settings.php` for a `db_cachedir` setting... it should be a directory.)
