### ISSUE TITLE
LDAP admin login not working

### ISSUE THREAD

**Issue by criskolkman** [craigk5n/webcalendar#192]
Hello,

I'm trying to implement the calendar for our team but we are having issues with the LDAP admin login, it's just not working.
When I login as a user which is member of the group defined at `$ldap_admin_group_name`, that user can login but is not an admin user.
Is it also possible to restrict normal user logins to a specific group (eg: SEC_COMP_WebCalendar-Users) instead of all the AD accounts?

I have to say, we are using Active Directory to accomplish this.

Below is my **user-ldap.php** file.

```
/***************************** Config *******************************/
// Set some global config variables about your system.
// Next three are NOT yet implemented for LDAP
$user_can_update_password = false;
$admin_can_add_user = false;

// Allow admin to delete user from webcal tables
$admin_can_delete_user = true;
$admin_can_disable_user = false;

//------ LDAP General Server Settings ------//
//
// Name or address of the LDAP server
//  For SSL/TLS use 'ldaps://localhost'
$ldap_server = '192.168.200.2';

// Port LDAP listens on (default 389)
$ldap_port = '389';

// Use TLS for the connection (not the same as ldaps://)
$ldap_start_tls = false;

// If you need to set LDAP_OPT_PROTOCOL_VERSION
$set_ldap_version = false;
$ldap_version = '3'; // (usually 3)

// base DN to search for users
$ldap_base_dn = 'OU=COMPANY_NAME,DC=COMPANY_NAME,DC=com';

// The ldap attribute used to find a user (login).
// E.g., if you use cn,  your login might be "Jane Smith"
//       if you use uid, your login might be "jsmith"
$ldap_login_attr = 'sAMAccountName';

// Account used to bind to the server and search for information.
// This user must have the correct rights to perform search.
// If left empty the search will be made in anonymous.
//
// *** We do NOT recommend storing the root LDAP account info here ***
$ldap_admin_dn = 'CN=WebCalendar Service,OU=Service Accounts,OU=COMPANY_NAME,OU=COMPANY_NAME,DC=COMPANY_NAME,DC=com';  // user DN
$ldap_admin_pwd = 'PASSWORD'; // user password

//------ Admin Group Settings ------//
//
// A group name (complete DN) to find users with admin rights
$ldap_admin_group_name = 'CN=SEC_COMPANY_NAME_WebCalendar-Admins,OU=Webservices,OU=Global groups,OU=COMPANY_NAME,DC=COMPANY_NAME,DC=com';

// What type of group do we want (posixgroup, groupofnames, groupofuniquenames)
$ldap_admin_group_type = 'posixgroup';

// The LDAP attribute used to store member of a group
$ldap_admin_group_attr = 'member';

//------ LDAP Filter Settings ------//
//
// LDAP filter used to limit search results and login authentication
$ldap_user_filter = '(objectclass=person)';

// Attributes to fetch from LDAP and corresponding user variables in the
// application. Do change according to your LDAP Schema
$ldap_user_attr = array (
  // LDAP attribute   //WebCalendar variable
  'sAMAccountName',              //login
  'sn',               //lastname
  'givenname',        //firstname
  'cn',               //fullname
  'mail'              //email
);

/*************************** End Config *****************************/
```

**Comment by criskolkman** [comment]
@craigk5n is this a known issue?

**Comment by criskolkman** [comment]
Strange thing is that when I `print_r($cached_admins)`, I do get the correct users.

`Array ( [0] => CN=Admin NAME,OU=Admin,OU=COMPNAME,DC=COMPNAME,DC=com )`

**Comment by criskolkman** [comment]
Okay so the admin lookup is not correct.
When I change `$ldap_login_attr` to `$ldap_login_attr = 'cn';` and `$ldap_admin_group_type` to `$ldap_admin_group_type = 'groupofnames';`, the `print_r($cached_admins)` returns `Array ( [0] => Admin FIRSTNAME LASTNAME )` (user full name).

When this happens, I'm admin and everything is okay, but this means I have to login with full name instead of sAMAccountName, which should not happen.

**Comment by criskolkman** [comment]
So a tiny step further now...

When I `print_r($ret)`, the account I'm logged in with is an admin, but the application still thinks I'm not...

```
Array
(
    [0] => Array
        (
            [cal_login] => my_sAMAccountName
            [cal_lastname] => my_lastname
            [cal_firstname] => my_firstname
            [cal_email] => my_email
            [cal_is_admin] => Y
            [cal_fullname] => my_fullname
        )

)
```

**Comment by criskolkman** [comment]
The var `$login_is_admin` returns `N` while it should be `Y` (see output above).
I also cannot see where the var `$login_is_admin` is getting it's value from, I can only find:

```
root@webserver02:/var/www/sub.domain.com/web# grep -R '$login_is_admin'
includes/classes/WebCalendar.class:    $login_email, $login_firstname, $login_fullname, $login_is_admin,
includes/classes/WebCalendar.class:          $is_admin = ( $login_is_admin == 'Y' );
root@webserver02:/var/www/sub.domain.com/web#
```

**Comment by criskolkman** [comment]
Fixed an error in user-ldap.php.

OLD:
```
$GLOBALS[$prefix . 'is_admin'] = user_is_admin ($login,get_admins ());
```

NEW:
```
$GLOBALS[$prefix . 'is_admin'] = user_is_admin ($info[0][strtolower($ldap_user_attr[5])][0],get_admins ());
```

And my `$ldap_user_attr` is:
```
$ldap_user_attr = array (
  // LDAP attribute     //WebCalendar variable
  //'uid',              //login
  'sAMAccountName',     //login
  'sn',                 //lastname
  'givenname',          //firstname
  'cn',                 //fullname
  'mail',               //email
  'distinguishedName'
);
```

**Comment by craigk5n** [comment]
So was your solution unique to your LDAP configuration?  Or is this a change that should be made to the code base?

**Comment by criskolkman** [comment]
> So was your solution unique to your LDAP configuration? Or is this a change that should be made to the code base?

Hello @craigk5n,

Well the original `user-ldap.php` uses `uid` to login and in the `$ldap_user_attr`, but I'm using Microsofts Active Directory and `uid` is not an attribute, so I had to replace it with `sAMAccountName`.

I suppose everyone running ADDS will run into this issue.

I also fixed my question regarding to restrict logins in my original post:
```
Is it also possible to restrict normal user logins to a specific group (eg: SEC_COMP_WebCalendar-Users) instead of all the AD accounts?
```

To accomplish this you can change the `$ldap_user_filter` in the file `user-ldap.php` like my example below.
In this example I added 2 groups to the filter (also the admin group defined at `$ldap_admin_group_name`), if a user is member of 1 of these groups (this is an OR filter), they have access to the calendar (this is an ADDS filter, I don't know if this works on ADDS alternatives).

```
$ldap_user_filter = '(&(|(memberOf=CN=SEC_COMPNAME_WebCalendar-Admins,OU=Webservices,OU=Global groups,OU=COMPNAME,DC=COMPNAME,DC=com)(memberOf=CN=SEC_COMPNAME_WebCalendar-Users,OU=Webservices,OU=Global groups,OU=COMPNAME,DC=COMPNAME,DC=com)))';
```
