### ISSUE TITLE
error when registering a new user

### ISSUE THREAD

**Issue by eduardochagas** [craigk5n/webcalendar#198]
on PHP 7, using xampp,  when we click on Settings and select the option User Manager, when trying to create a new user for the administration of the application, this error appears:

<br />
<b>Notice</b>:  Trying to access array offset on value of type null in <b>/opt/lampp/htdocs/agendaWeb/ajax.php</b> on line <b>50</b><br />

i need so much this application to my project of the course. If you could help me...

**Comment by craigk5n** [comment]
Fixed the PHP warning for this in latest commit
