### ISSUE TITLE
Broken link in the installer (User Supported Wiki)

### ISSUE THREAD

**Issue by ledav-net** [craigk5n/webcalendar#199]
Hi,

Not very important but there is a broken link in the installer.
I'm using the git repo on the master branch (last commit: 49dc5f1f)

/install/index.php
Link: User Supported Wiki

http://www.k5n.us/wiki/
Not Found
The requested URL /wiki/ was not found on this server.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
Apache Server at www.k5n.us Port 80

Regards,
David.

**Comment by craigk5n** [comment]
Fixed with latest commit

**Comment by ledav-net** [comment]
Thanks :-)
