### ISSUE TITLE
set_magic_quotes_runtime() used in installer of v1.2.9 

### ISSUE THREAD

**Issue by feeela** [craigk5n/webcalendar#203]
The installer of the current stable release (v.1.2.9) does not work with recent PHP versions (e.g. 7.3), since it uses `set_magic_quotes_runtime()`, which was deprecated since PHP v5.3 and removed from PHP in v7.0 (see: https://www.php.net/set_magic_quotes_runtime)

Error message when trying to install the database: `Call to undefined function set_magic_quotes_runtime() in /kunden/181961_12047/webseiten/termine.blaueblume.de/install/install_functions.php:458`

Nonetheless the docs state that "WebCalendar 1.2 is the latest production release" and "PHP 7.1 or later" is required. Downloaded the release from the github releases page: https://github.com/craigk5n/webcalendar/releases

**Comment by craigk5n** [comment]
This has been fixed in the main branch now, but there has not been a release yet.  You can download the latest code for the fix.
