### ISSUE TITLE
 The each() function is deprecated error in edit view (view_entry.php)

### ISSUE THREAD

**Issue by marcnyc2001** [craigk5n/webcalendar#206]
using the latest webcalendar 1.3.0 when I click on some (not all) multi-day even to view or edit I see this error at the top of the event details (under the title):

`Deprecated: The each() function is deprecated. This message will be suppressed on further calls in /home/marcurse/public_html/_OTHERSITES/saanenmoeser/includes/xcal.php on line 427`

**Comment by craigk5n** [comment]
Fix is in main branch now.

**Comment by marcnyc2001** [comment]
The fix addressed this in view_entry.php however I wanted to point out that I also get this error in the admin.php page:

`Deprecated: The each() function is deprecated. This message will be suppressed on further calls in /home/public_html/webcal/admin.php on line 20`
