### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by craigk5n** [craigk5n/webcalendar#211]
I'm planning on rewriting the UI for WebCalendar.  Considering Boostrap+jQuery.  Comment below with ideas.

More info [here](https://www.k5n.us/2020/09/02/new-webcalendar-ui/).

**Comment by t1mothy666** [comment]
Much appreciated - I'm exited!

**Comment by criskolkman** [comment]
Hello @craigk5n 

Awesome news that you want to improve the UI!
Maybe a look something like this would be nice? https://codepen.io/nijin39/pen/JbQBXM

Keep up the great work!

**Comment by tuaris** [comment]
A UI update would be nice.  Can you try to make sure that this doesn't result in a mess of external dependencies?  One of the things I like about this PHP application is how simple it is to install, no need to deal with composer or npm.  Just download an archive and unzip.  I really want it to stay that way.

**Comment by craigk5n** [comment]
Updated UI is now in the bootstrap-ui branch.  This will eventually get merged into master with some further testing.

**Comment by s22-tech** [comment]
This suggestion may be too late now, but how about using Bootstrap 5?  That way you could eliminate the requirement for jQuery.  That would be nice - unless, of course, you need it for something else.  

There are [other benefits](https://superdevresources.com/bootstrap5-vs-bootstrap4-whats-new/), as well.

Thanks!
