### ISSUE TITLE
Menu display error

### ISSUE THREAD

**Issue by kesien** [craigk5n/webcalendar#213]
For some reason 2 menu items are showing some html code. See image below
![webcalendar](https://user-images.githubusercontent.com/66409501/93309254-95339f00-f803-11ea-8520-0ed1df905278.PNG)

Can someone help?

**Comment by craigk5n** [comment]
Which version of WebCalendar are you using?  I'm not seeing that in the latest code, but it may be due to different settings resulting in different menu options.

**Comment by craigk5n** [comment]
I think this may be fixed with a recent commit to the master branch.  Please re-open if you are still seeing this with the latest code.
