### ISSUE TITLE
Add Exception/Add Inclusion not working

### ISSUE THREAD

**Issue by charmedones** [craigk5n/webcalendar#216]
I have loaded 1.3 Version and everything seems to be a simple fix, but I can't see to get the Exclusions/ inclusions to work. You can select the day in the pop up calendar, but you can't click the add
This is V 1.3 on PHP 7.3 Apache.
Any one have a solution to this?

**Comment by craigk5n** [comment]
Wow, this appears to have been broken for a while.  I'm surprised no one has noticed until this point.  About to post a fix for it.  Thanks.
