### ISSUE TITLE
PHP Warning:  A non-numeric value encountered in /WebSchedule/includes/functions.php on line 6223

### ISSUE THREAD

**Issue by charmedones** [craigk5n/webcalendar#217]
V 1.3 on PHP 7.3 
When we use the site_extra.php
we get the error above
When we blank it out the error disappears

$ret = [];
  $extra_view = 1;
  foreach ( $site_extras as $site_extra ) {
    $data = '';
    $extra_name = $site_extra[0];
    $extra_desc = $site_extra[1];
    $extra_type = $site_extra[2];
    $extra_arg1 = $site_extra[3];
    $extra_arg2 = $site_extra[4];
    if ( ! empty ( $site_extra[5] ) && ! empty ( $filter ) )
      $extra_view = $site_extra[5] & $filter;
    if ( ! empty ( $extras[$extra_name] ) && !
        empty ( $extras[$extra_name]['cal_name'] ) && ! empty ( $extra_view ) ) {
      $name = translate ( $extra_desc );

**Comment by craigk5n** [comment]
Should be fixed now with this latest code change on the master branch.  Let me know if you're still seeing the issue.
