### ISSUE TITLE
"Include add event link in views"  has no effect

### ISSUE THREAD

**Issue by adam12b1** [craigk5n/webcalendar#220]
In 1.3 release tarball or latest Git master, changing the `ADD_LINK_IN_VIEWS` config setting to `Y` (controlled via the "Include add event link in views" option under **System Settings**) has no effect, the `+` buttons are still not displayed.

Running PHP 7.4.12, with all other settings at defaults.

**Comment by craigk5n** [comment]
A better description of this option would be "Allow adding events from view".  This option enables/disables adding events from the custom views (view_m.php, view_w.php, etc.). If set to 'No', these views are read-only and users must go to a standard view (month.php, etc.) to add an event.  So the code is working as designed, but it's not properly communicated.

If you are just looking to add back the new event '+' icon, that's an open issue #152 making this a duplicate.
