### ISSUE TITLE
deprecated

### ISSUE THREAD

**Issue by HiroProtago** [craigk5n/webcalendar#222]
Hi I installed the current version 1.3 of the web calendar on my webspace with PHP 7.4. 
Error messages appear during the installation: 
Deprecated: Function get_magic_quotes_gpc() is deprecated in /home/www/webcal/includes/formvars.php on line 112 
Deprecated: Function get_magic_quotes_gpc() is deprecated in /home/www/webcal/includes/formvars.php on line 81 

But the installation wizard shows green everywhere. 
No user with a password is created during the installation. If I call up the calendar and enter any password, error messages similar to those during the installation appear: 
Deprecated: Function get_magic_quotes_gpc() is deprecated in /home/www/webcal/includes/formvars.php on line 81 
Deprecated: Function get_magic_quotes_gpc() is deprecated in /home/www/webcal/includes/formvars.php on line 81 
Deprecated: Function get_magic_quotes_gpc() is deprecated in /home/www/webcal/login.php on line 90 
Warning: Cannot modify header information – headers already sent by (output started at /home/www/webcal/includes/formvars.php:81) in /home/www/webcal/login.php on line 140 
Warning: Cannot modify header information – headers already sent by (output started at /home/www/webcal/includes/formvars.php:81) in /home/www/webcal/login.php on line 146 

What can I do? 
Kind regards Tim

**Comment by craigk5n** [comment]
Fixed in commit 1f862ec
