### ISSUE TITLE
PHP 7.4 support - Function get_magic_quotes_gpc() is deprecated

### ISSUE THREAD

**Issue by lkppo** [craigk5n/webcalendar#227]
Sending form http://webcalendar.test/install/index.php with a blank password I get this error, twice:

( ! ) Deprecated: Function get_magic_quotes_gpc() is deprecated in C:\WinNMP\WWW\webcalendar\includes\formvars.php on line 81
--

1 | 0.0070 | 619392 | {main}(  ) | ...\index.php:0
2 | 0.6190 | 1316056 | getPostValue(  ) | ...\index.php:226

**Comment by craigk5n** [comment]
Please try the latest code from the git repo.  This issue should be resolved now.  I've removed all calls to get_magic_quotes_gpc in the code.

**Comment by lkppo** [comment]
Ok, I will do it later this day.

What is the PHP min version required or you expect to support?

I could help you to support 7.x versions in a systematic way.
