### ISSUE TITLE
Uncaught ReferenceError: validate_and_submit is not defined

### ISSUE THREAD

**Issue by tuaris** [craigk5n/webcalendar#231]
I am unable to add events.  

For example if I go to http://webcal-server.domain.tld/edit_entry.php fill in the fields and press "Save" nothing happens.  If I look at the web browser's console output I see:

```
Uncaught ReferenceError: validate_and_submit is not defined
    onclick http://webcal-server.domain.tld/edit_entry.php:1
```

I am using 1.3.0.

Also, I'm not not seeing the *+* icons on the calendar itself to add an event.  They are missing.

**Comment by tuaris** [comment]
I noticed in the console error output these additional messages when loading the page:

```
Uncaught SyntaxError: unexpected token: identifierjs_cacher.php:745:27
Uncaught ReferenceError: onLoad is not defined
    onload http://webcal.morante.net/edit_entry.php?date=20210226&defusers=:1
edit_entry.php:1:1
```

I think the issue might be in the Javascript function `catOkHandler()` generated from `includes/js/edit_entry.php`.  Looking closer at the code... I noticed something. I have a category named "Manager's Schedule".  The generated Javascript code in the browser looks like this:

```
      catIds += '8';
      catNames += 'Manager's Schedule';
```

PHP code looks like this in `includes/js/edit_entry.php`:

```
      catIds += '<?php echo $catid;?>';
      catNames += '<?php echo $cat['cat_name'];?>';
```

The single quote needs to be escaped.  You can probably just wrap the variable in the `addslashes()` function

```
      catIds += '<?php echo $catid;?>';
      catNames += '<?php echo addslashes($cat['cat_name']);?>';
```

After doing that, I was able to create an event

**Comment by craigk5n** [comment]
Fixed with merged PR
