### ISSUE TITLE
How do I launch the Calendar?

### ISSUE THREAD

**Issue by Hazekaya** [craigk5n/webcalendar#239]
After installation when pressing the _Launch Calendar_ button it just opens the installation page in a new tab and the _Launch Calendar_ button isn't here anymore.

What should I do? The installation was a success otherwise.

**Comment by craigk5n** [comment]
Try the following:
- Just open up a browser and go to the main webcalendar index.php page (not the installer) and see if that works.
- Check the webcal_config table and see what version is in there.  Use the following SQL to find it:
  `select * from webcal_config where cal_setting = 'WEBCAL_PROGRAM_VERSION';`
- Try installing 1.9.1 if you are using 1.9.0.

**Comment by craigk5n** [comment]
Closed since this is now a year old.
