### ISSUE TITLE
edit_entry_handler.php reports "503 Service Unavailable"

### ISSUE THREAD

**Issue by BurnHigh** [craigk5n/webcalendar#240]
The Error occurs when the discription of one "meeting" is (for me?) to long.

Here is the ErrorMassage:

_<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Unavailable</title>
</head><body>
<h1>Service Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
</body></html>_

The Server is **not** in maintenance mode and how do i know, how much capacity a "meeting" has?

There is a Systemsetting that says: Length of Shortdiscription, but it looks not as the right thing to handle the "capacity problem"

![image](https://user-images.githubusercontent.com/85177061/123542434-f2bd2a80-d749-11eb-8fbb-75053930cc10.png)

I hope someone can help me :)

**Comment by BurnHigh** [comment]
Update: Is there a "profanity"-Filter such that E-Mails like: "E-Mail: xxx**@gmx.de**" triggering this thing? The ErrorMassage as .txt-File "edit_entry_handle.php" is downloading when i try to type that in and press "save"

**Comment by craigk5n** [comment]
There is no filter in use.  Were you able to resolve the issue here?  What does the server error log say?

(Please re-open this issue if you are still having this problem.)
