### ISSUE TITLE
Emphasis not showing in French

### ISSUE THREAD

**Issue by guillaumearnx** [craigk5n/webcalendar#245]
Hello, special caracters like 'é', 'è', 'à' are not showing in French language.
I've try to change language to French and French (UTF-8) bot nothing changed ...

Thank's 
![emp](https://user-images.githubusercontent.com/37373941/132967607-4bac04a2-3dd1-4bd4-bcce-f3dc128b50cf.PNG)

**Comment by Nounours13** [comment]
Bonjour,
Changez dans le fichier French-UTF8.txt à la ligne 27 _"charset: UTF-8"_ par

**charset: Windows-1252**

et sélectionnez : 
 -  Dans le menu "Réglages" -> "Réglage du système" -> dans l'onglet "Réglages" -> "langue"  francais (UTF8)
 
![image](https://user-images.githubusercontent.com/12816315/134139135-386b4218-356c-4089-9b0f-ff247a13b686.png)

 -  Dans le menu "Réglages" -> "Préférences" -> dans l'onglet "Réglages" -> "langue" -> Francais (UTF8)
 
![image](https://user-images.githubusercontent.com/12816315/134138902-07110506-6227-4ba9-9df0-274aea0504f5.png)

**N'oubliez pas d'enregistrer à chaque fois les paramètres.**

Déconnectez vous et faites un rafraichissement.

Pour moi ça a marché.

Bonne journée

**Comment by guillaumearnx** [comment]
Merci beaucoup
