### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by zidingz** [craigk5n/webcalendar#248]
Hey there!

I belong to an open source security research community, and a member (@hitisec) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by craigk5n** [comment]
Please send security reports to my email: craig --at-- k5n.us

**Comment by JamieSlome** [comment]
@craigk5n - thanks for your support here! 👍 

Could you kindly take a look at the reports that still require fix confirmations against them?

https://huntr.dev/users/craigk5n/repositories/
