### ISSUE TITLE
:shield: Security vulnerabilities

### ISSUE THREAD

**Issue by hitisec** [craigk5n/webcalendar#249]
Hi, 
Some potential security vulnerabilities has been identified in this repository.
Please Validate reports submitted on huntr and if are valid please mark them valid there.
The report links are the following:  

https://huntr.dev/bounties/6d3abed2-cb23-4690-9410-064d506150cf/
https://huntr.dev/bounties/67546d0c-900f-4b88-8a1c-4a90a73a2ab6/
https://huntr.dev/bounties/08f81713-8bf2-425f-8781-0d51ba472e31/
https://huntr.dev/bounties/25abd226-1f34-442e-9c5a-25dcdc66604c/
https://huntr.dev/bounties/805fe5a2-90f8-478c-be59-ebdbe13bcfd9/

**Comment by craigk5n** [comment]
All the issues listed above have been resolved in the bootstrap-ui branch and will be included in the next release.
