### ISSUE TITLE
Installation with Database MariaDB10 not possible?

### ISSUE THREAD

**Issue by lysathor** [craigk5n/webcalendar#255]
I did a fresh install. I used the latest files. I started the caldendar and configured PHP accordingly.
On the next step I tried to configure MariaDB. Webcalendar sees "MySQL (Improved)" but whatever I enter or how I configure MariaDB I cannot get it run. No helpful error messages though. I created the database using phpMyAdmin, gave the user all rights, but no success.
Then I used SQLight3. That seems to work. I finished installation.

The I tried to create new user or calendar, but always get "Invalid referring URL". I will create a separate issue for that.

**Comment by craigk5n** [comment]
I've tested MariaDb 10.5 using the provided docker-compose.yml file, and it does work.  I'm not sure what the issue you are having is, but it is not an issue with Maria 10.5 support.
