### ISSUE TITLE
Problem installing 1.9.0

### ISSUE THREAD

**Issue by s22-tech** [craigk5n/webcalendar#265]
After setting a password on the first page (Create Settings File Password), I get this error and can't proceed any further:

```
Warning: Undefined array key "csrf_form_key" in /home/webcal/includes/formvars.php on line 46
WebCalendar Error

Fatal Error: Invalid form request
```

**Comment by s22-tech** [comment]
I was able to get beyond that point by commenting out this section of /includes/formvars.php:
```
if ($formKey == $_SESSION['csrf_form_key'] && !empty($_SESSION['csrf_form_key'])) {
      // Okay to proceed
   //echo "FORM KEY: $formKey \n"; exit;
}
else {
   die_miserable_death(translate('Fatal Error') . ': '
    . translate('Invalid form request') );
}
```

After installing the db, it got to page 3, showed a blank page, and then stalled:
https://my-webcalendar.com/install/index.php?action=install&page=3


Manually entering https://my-webcalendar.com/install/index.php in my browser got me to page 4, which then showed these errors:

**Warning:** Undefined array key "admin_exists" in **/home/webcal/install/index.php** on line **1536**
**Warning:** Undefined array key "server_url" in **/home/webcal/install/index.php** on line **1550**

I then selected the Create Default Admin Account box which showed "(Admin Account Not Found)"

Clicking the Launch WebCalendar button open a new window at https://my-webcalendar.com/install/index.php?action=mismatch&version=UNKNOWN
and won't let me out of the install script.  I'm stuck in an endless install loop.


Some other thoughts:

1] When I entered my server URL, I got the error message: "Server URL must end with a slash(/)."  Why can't the script add it itself?  It seems to know it's missing, so it would be nice if it automatically added it when needed.

2] I don't think all the modal dialog boxes that pop up for every page during installation are necessary.  Having to clear away those modals makes installation more time-consuming than it needs to be.  Simply going to the next page upon successful completion of a step should be sufficient.

**Comment by craigk5n** [comment]
Fixed in master branch.  Will re-issue 1.9.1 release to address this.

**Comment by craigk5n** [comment]
See new 1.9.1 release.  This will fix the CSRF error and removes the includes/settings.php file that was included improperly.

**Comment by s22-tech** [comment]
1.9.1 doesn't seem to have the updated /install/index.php file.

**Comment by craigk5n** [comment]
You are correct @s22-tech .  I didn't do a `git pull` before packing up the zip and tar.gz files.  I have updated the release to with a new zip and tar.gz file which should have the updated install/index.php file.

**Comment by s22-tech** [comment]
I also see this message on step 4:
`HTTP-based authentication was not detected. You will need to reconfigure your web server if you wish to select 'Web Server' from the 'User Authentication' choices below.`
however, I have None(Single-User) selected.

Is there some setting on the server I need to change?  Perhaps something in the .htaccess?

**Comment by s22-tech** [comment]
I was finally able to install this script using the latest master version.
