### ISSUE TITLE
Unable to login since upgrade to v 1.91

### ISSUE THREAD

**Issue by AlbaVore** [craigk5n/webcalendar#289]
I have webcalendar installed here:
http://www.thegorbals.co.uk/thegorbalscalendar/login.php

I had upgraded to the latest version and the upgrade went without an issue.
the database connected and the calendar functions as it should.
However the users in the database do not allow me to login. The default login does not work. I cannot administer the calendar.
The issue appears to be password related as the login recognises wrong or invalid users. But it does not recognise valid passwords even though they are input as they are in the web users in the tables of the database.

The version of PHP is the latest 7.4.24. I have tried deprecating back through versions of php but to no avail.

I have deleted and reinserted users and passwords in the database.

The upgrade was quite straightforward so I have run out of ideas as to why this is not working. I only get 'Incorrect password' at the login.

I'd really appreciate any assistance.

**Comment by AlbaVore** [comment]
Hello, Thanks to excellent support from the hosting company I have managed to resolve this issue.
Basically they changed the webcal_user password type change from varchar(32) to longtext(100).

Is this a known issue? Probably not but hopefully spitting it here may assist other users who come across this issue.

**Comment by craigk5n** [comment]
The upgrade process (install/index.php) is supposed to automatically update the password to the new stronger type.  If not done there, there is some code in includes/users.php that is support to do the update on the next login.

**Comment by AlbaVore** [comment]
Ok thanks for the information. Will remember it for other possible installs.

**Comment by AlbaVore** [comment]
Hello again, Just to add that this issue has reemerged.

I cannot login to the admin account. The install of the calendar was straightforward enough and the calendar is loading fine. If only I could access the admin to allow me to update and amend things. Can anyone advise please?

I have removed the database, reloaded the application a couple of times. The database and application are connecting fine other than this login issue. There is only one user and one password int he database. Those credentials are not allowing me to access the admin.

I have tried a previous resolution of changing the password type to LONGTEXT 100 rather than the VARCHAR 35. This has not affected anything.

I am going round in circles with this. Its quite dispiriting. Any help would be most welcome. What am I missing here?

**Comment by AlbaVore** [comment]
Hello,

Just to say that in phpmyadmin I changed the password type to varchar (255) and then with MD5 in the function tab for the admin user. This worked and allowed me to login. A real relief.

Hope this helps someone else with the same issue.

**Comment by Fjorstut** [comment]
Same here. Installed v1.9.1 today, got around the curly brackets issue (php 8.1), but then was not able to log in properly. Tried @AlbaVore solution with varchar255, and managed to log in with admin account, however no success with my actual user account.
My conclusion as-is is to stay on php7.1 av webcalendar 1.3 until further. It's a pity because it means I cannot run more up-to-date applications, like Wordpress, as the same domain as my webcalendar.
This just for info, while I am eagerly awaiting a Webcalendar version which will work on the latest PHP versions.

**Comment by craigk5n** [comment]
1.9.8 works with PHP 8 now.

**Comment by marcnyc2001** [comment]
Thank you for posting this solution. The LONGTEXT solution worked for me as well. I was able to login as as admin/admin (username/pw) and then change the password of my existing user
