### ISSUE TITLE
Error in install/index.php and/or include/formvars.php

### ISSUE THREAD

**Issue by Spamdoos** [craigk5n/webcalendar#315]
PHP 8.1 - Ubuntu 22.04.01

Apache error message (error.log):
 PHP Warning:  Undefined array key "csrf_form_key" in /***/www/cal-***.nl/includes/formvars.php on line 46, referer: https://cal.***.nl/install/index.php
PHP Warning:  Undefined array key "csrf_form_key" in /***/www/cal-***.nl/includes/formvars.php on line 47, referer: https://cal.***.nl/install/index.php

**Comment by thestaz** [comment]
Well, here it is Nov 20 and no one has responded.  I have the same problem.  Anyone figured this out yet?

**Comment by craigk5n** [comment]
This should be fixed now.  PHP 8 was not yet supported in 2022.
