### ISSUE TITLE
Webcal to FB automation

### ISSUE THREAD

**Issue by mgaulton** [craigk5n/webcalendar#320]
Anyone know of a way to autocreate Facebook Events in a group based on new events in Webcalendar?
Just trying to see if I can save a couple of steps?

**Comment by craigk5n** [comment]
You could make the calendar available as ICS (publish it in System Settings and User Preferences).  I don't believe supports any kind of ICS import, so you (or someone) would need to write some custom code to add an event probably using the FB SDK:

https://developers.facebook.com/docs/graph-api/reference/v11.0/event
