### ISSUE TITLE
UTF-8 support for database (WebCalendar 1.2.8)

### ISSUE THREAD

**Issue by codifex** [craigk5n/webcalendar#33]
I wanted to convert a WebCalendar 1.2.7 install (latin1 encoding) to WebCalendar 1.2.8 (UTF-8).

To do so I made an SQL dump, replaced "=latin1;" with "=utf8;" and imported the SQL file using phpMyAdmin.  I am unsure if this is sufficient.  In addition, I enabled UTF-8 in WebCalendar's German translations file.

However, entries containing umlauts etc. are missing in the calendar.

I found out that the mySQL server's `character_set_server` is set to `latin1`.  Unfortunately I am not allowed to change this setting.

Thus the character set must be overridden after the connection to the SQL server has been established using this server default.

I was able to fix the problem by editing "dbi4php.php" and adding a new line 124 containing `mysqli_set_charset($c, "utf8");`.

I just want to make sure that this is currently the way to go.  Or is there any other solution/setting I missed?

Any recommendations on the right choice of the database character set ('utf8' vs. 'utf8mb') are appreciated too.

**Comment by codifex** [comment]
My tests with WebCalendar 1.2.9 revealed that currently setting the database's and the connection's encoding to 'utf8' alongside with setting WebCalendar's translation to UTF-8 allow for support of umlauts in calendar entries.

Unfortunately using 'utf8mb4' does not yet work, which would be preferable from a technical point of view (WordPress already switched to this encoding, Piwik is also planning to do so).

**Comment by craigk5n** [comment]
This is an issue of how you create your WebCalendar database rather than the WebCalendar code.
Perhaps the documentation should be updated to note that if you use the default MySQL encoding, it may not support UTF8.
