### ISSUE TITLE
Default access type should be configurable

### ISSUE THREAD

**Issue by elacour** [craigk5n/webcalendar#335]
When creating a new entry, default access seems to be "C" (confidential). In fact, cal_access in webcal_entry table as a default value of "C". In edit_entry.php,  the field as all values selected for a new entry ($access undefined). It would be nice to add an admin config for choosing the default value (here we use public by default).

**Comment by craigk5n** [comment]
Good idea!

**Comment by craigk5n** [comment]
Implemented in master branch and should be in 1.9.10
