### ISSUE TITLE
Install wizard return 500 on database test (PHP 8.2)

### ISSUE THREAD

**Issue by meyer-solutions** [craigk5n/webcalendar#346]
I can't finish the Install wizard after upgrading from PHP 74. to 8.2.
The database test is showing an empty window (HTTP status 500)
Database: mysqli 

An ideas on this?

Thanks in advance.

**Comment by craigk5n** [comment]
Check your Apache error log.

And what version of WebCalendar? Your version may not support that version of PHP.

**Comment by oranges13** [comment]
It definitely has issues with php 8+, looks like it is using several functions which were deprecated after PHP 7. (`PHP Fatal error:  Uncaught Error: Call to undefined function get_magic_quotes_gpc()`)

**Comment by craigk5n** [comment]
This has been fixed in v1.9.8.  My dev environment is now PHP 8.2, so hopefully I caught most (or all) of the PHP 8 issues.
