### ISSUE TITLE
PHP Fatal error:  Cannot redeclare preventhacking() in \x18\xb7,\xe3ZU on line 21

### ISSUE THREAD

**Issue by htukiain** [craigk5n/webcalendar#35]
In webserver error log plenty of preventhacking on line 21.
Endresult is that login page gives 500 error and I can not  login.
About 1/5th of refereshes gives ok response, 4/5 gives 500 error from login page.

[Mon Aug 21 20:58:44.022136 2017] [:error] [pid 5233] [client 91.152.167.194:57134] PHP Fatal error:  Cannot redeclare preventhacking() in \x18\xb7,\xe3ZU on line 21, referer: xxxxx /month.php
[Mon Aug 21 20:58:47.679431 2017] [:error] [pid 5236] [client 91.152.167.194:57137] PHP Fatal error:  Cannot redeclare preventhacking() in \xf8\xabs\xe3ZU on line 21,

**Comment by htukiain** [comment]
This was fixed by commenting out preventHacking-function in formvars.php.
Now some PHP notifications appear, but no PHP fatal errors.

**Comment by htukiain** [comment]
This was fixed by commenting out preventHacking-function in formvars.php.
Now some PHP notifications appear, but no PHP fatal errors.

**Comment by craigk5n** [comment]
Which version/branch of webcalendar is this?

**Comment by htukiain** [comment]
v 1.2.7 - actual production site: http://suunnistus.tampereenpyrinto.fi/kalenteri/month.php

**Comment by craigk5n** [comment]
It sounds like formvars.php is being included more than once.  A fix would be to change all the include statements to be include_once.  It's not clear why you are able to generate this error and others (me) are not...

**Comment by craigk5n** [comment]
Give the changes in the devel-1.2 branch a try.  I replaced all the include statements with include_once.  I'm thinking that will fix this.  (I tried but could not recreate this issue.)

**Comment by htukiain** [comment]
formvars.php has new added function in dev prevetHacking_helper. I changed that to production and issues dissapeared. Seems to work!

**Comment by htukiain** [comment]
Same site but fresh 1.3 code in production and error is back!

**What I did:**
Removed the old code, copied the V1.3 from Github. All worked fine for 24 hours, but now the error is back.

**Error log**
[Tue Oct 03 22:04:26.958221 2017] [:error] [pid 3159] [client 158.69.254.103:56440] PHP Fatal error:  Cannot redeclare preventhacking_helper() in  })\x95.V on line 21
[Tue Oct 03 22:04:33.188977 2017] [:error] [pid 3156] [client 158.69.254.103:40626] PHP Fatal error:  Cannot redeclare preventhacking_helper() in P*\xd9\x94.V on line 21
[Tue Oct 03 22:04:39.158597 2017] [:error] [pid 3230] [client 158.69.254.103:53106] PHP Fatal error:  Cannot redeclare preventhacking_helper() in \xc0of\x95.V on line 21
[Tue Oct 03 22:04:44.538423 2017] [:error] [pid 3159] [client 158.69.254.103:35918] PHP Fatal error:  Cannot redeclare preventhacking_helper() in  \xcf\xe0\x94.V on line 21
[Tue Oct 03 22:04:48.326841 2017] [:error] [pid 2880] [client 158.69.254.103:43958] PHP Fatal error:  Cannot redeclare preventhacking_helper() in \x10\x14\xae\x95.V on line 21
[Tue Oct 03 22:04:52.736011 2017] [:error] [pid 2847] [client 158.69.254.103:52520] PHP Fatal error:  Cannot redeclare preventhacking_helper() in \xc0Z\xf6\x94.V on line 21
[Tue Oct 03 22:04:59.583713 2017] [:error] [pid 3197] [client 158.69.254.103:34764] PHP Fatal error:  Cannot redeclare preventhacking_helper() in `\xa2\x87\x94.V on line 21
[Tue Oct 03 22:05:04.687037 2017] [:error] [pid 3202] [client 158.69.254.103:46960] PHP Fatal error:  Cannot redeclare preventhacking_helper() in \x10\x9fB\x95.V on line 21
[Tue Oct 03 22:05:10.030088 2017] [:error] [pid 3351] [client 158.69.254.103:58216] PHP Fatal error:  Cannot redeclare preventhacking_helper() in  on line 21

**Unclear error cause**
Error happens around 50 % of the cases. For me this implies that the code is right, but some caching or similar type of functionality is mixing things up. Wondering what that could be.

**Solutions tested:**
* cleaned TMP-folder
* include_once for formvars.php

**Comment by WayneSallee** [comment]
I've been using Web Calendar for many years, and just now ran into this problem.
I fixed it by doing the following:

####################
# Open includes/formvars.php
# Add the first line:
if (!function_exists('preventHacking'))   {
function preventHacking ( $name, $instr ) {


# Then at the end of the function add the extra }:
    }
  }
}}
###############

I do have my calendar modified so that it is impossible to log in from the normal direction. So that could put me at a higher risk for this. But at least I have the fix for it. :-) Still seems strange that it would even happen in the first place. But it's fixed now. :-)

Wayne Sallee
Wayne@WayneSallee.com
