### ISSUE TITLE
Error 500 on Save

### ISSUE THREAD

**Issue by mgaulton** [craigk5n/webcalendar#353]
WebCalendar
version v1.9.1
(08 Mar 2022)

Every time I submit a new calendar item or save a modified event, I get an error 500. 
Interestingly, it creates/updates the event. Its just annoying me at the moment.
Its shared hosting so I'm not sure if I have access to any httpd logs.

**Comment by craigk5n** [comment]
Any chance you are/were using PHP8?  There have been a lot of issues with v1.9.1 and PHP8.  Please reopen with details from the apache error log (or whatever error log you have) if this is not the case.
