### ISSUE TITLE
Error when switching from PHP 7.4 to PHP 8.0

### ISSUE THREAD

**Issue by lissmann** [craigk5n/webcalendar#357]
WebCalendar 1.9.1

I am logged in and the calendar is showing as usual under PHP 7.4. When switching to PHP 8.0 and reloading the site it shows me an fatal error:

Fatal error: Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in .../includes/functions.php:4909

**Comment by craigk5n** [comment]
This should be fixed in the latest code in git.
