### ISSUE TITLE
PHP7 compatibility of WebCalendar 1.2.8

### ISSUE THREAD

**Issue by codifex** [craigk5n/webcalendar#36]
The release description says "Updates to supper PHP7".

Does "supper" mean "support" and WebCalendar 1.2.8 is fully compatible with PHP7?

**Comment by craigk5n** [comment]
The code changes for PHP7 are in the master branch (which will be part of 1.3.0), which is a different release.  Version 1.2.8 does not have the PHP7 changes in it.  The 1.2 releases are maintenance releases (security fixes mostly).
