### ISSUE TITLE
Installing webcalendar-master 1.9.1 on php8.1.12/Apache 2.4.56-1/MariaDB 10.4.26-1

### ISSUE THREAD

**Issue by Grover-D** [craigk5n/webcalendar#367]
Hello, 

I have used webcalendar before and wanted to install is on my current system. When I set it up and make the install directory 777, add the correct settings to settings.php in the include directory and run install/index.php I get:

Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/htdocs/webcalendar-master/includes/translate.php on line 342
...
Warning: session_start(): Session cannot be started after headers have already been sent in /var/www/htdocs/webcalendar-master/install/index.php on line 144

Deprecated: basename(): Passing null to parameter #1 ($path) of type string is deprecated in /var/www/htdocs/webcalendar-master/includes/formvars.php on line 26

Deprecated: preg_replace_callback(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/htdocs/webcalendar-master/includes/formvars.php on line 80

Deprecated: basename(): Passing null to parameter #1 ($path) of type string is deprecated in /var/www/htdocs/webcalendar-master/includes/formvars.php on line 26

Deprecated: preg_replace_callback(): Passing null to parameter #3 ($subject) of type array|string is deprecated in /var/www/htdocs/webcalendar-master/includes/formvars.php on line 80

I enter the new password to use, it totally dies. The errors for translate_php look to be related to not having a correct default language setting. And looking at the code and directions, safe_mode is no longer supported at all. 

Is webcalander supported for php 8.1.12?
Thanks - If you need more details please let me know.

**Comment by craigk5n** [comment]
Yes, I am planning on fixing these issues.

**Comment by craigk5n** [comment]
These issues should be fixed in v1.9.6.
