### ISSUE TITLE
PHP version support of WebCalender 1.2.8

### ISSUE THREAD

**Issue by codifex** [craigk5n/webcalendar#37]
Can WebCalendar 1.2.8 be used safely with PHP 5.6?

WebCalendar 1.2.7 IIRC only worked faultlessly with PHP 5.3.

I am planning to first update from 1.2.7 to 1.2.8 using PHP 5.3 and then switch to PHP 5.6.

P.S.: Is this the right place to ask questions like that?

**Comment by craigk5n** [comment]
Yes, this is the best place to ask.  PHP 5.6 is supported.  I would wait for 1.2.9 (hopefully this week) since there the PHP compile error in login.php (fixes in code on github).
