### ISSUE TITLE
Hidden macOS settings files in the release package (WebCalendar 1.2.8)

### ISSUE THREAD

**Issue by codifex** [craigk5n/webcalendar#38]
The WebCalendar 1.2.8 release package contains macOS setting files which should not be included in the release. These files are not shown on macOS, but they are visible on Windows and they have to be deleted manually before uploading the files from the release package to the server. The file names start with "._", e.g., "._GPL.html", "._favicon.ico", "docs/._newwin.gif", "icons/._example.gif", etc.

**Comment by craigk5n** [comment]
I have repackages 1.2.8 using zip (which doesn't include the hidden mac os files).  I also release 1.2.9 in the same manner and which also include the php compile error fix for login.php.
