### ISSUE TITLE
Allow opt-in for placing webcalendar within iframe

### ISSUE THREAD

**Issue by Tharrington86** [craigk5n/webcalendar#383]
I just upgraded to version 1.9.1 and I can no longer deploy the calendar across our network embedded into an iframe. 

Console error is as follows:
Refused to frame 'My URL' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".

Is this intended behavior? I need the ability to embed the calendar via iframe on our company intranet site.

**Comment by craigk5n** [comment]
Yes, this is an intended behavior for security reasons.  I'll change the title of this to opting in to allow this.

**Comment by Tharrington86** [comment]
That would be a great option to include, especially for us legacy users that are embedding the calendars in other webpages.

I am unfamiliar with php but if you could point me in the right direction, I will see what I can come up with.

**Comment by craigk5n** [comment]
Version 1.9.8 now has an option in Admin Setting under "Site security" where you can set the CSP value to allow use of iframes.

**Comment by Tharrington86** [comment]
I just tried to upgrade to v1.9.8 and everything went smooth except I still cannot get the calendar to display in an iframe. After I ran the installation wizard, I logged in to the calendar via the direct URL and selected to allow any site to iframe and disabled the origin checking. When trying to view the embedded calendar nothing is displayed and the following is displayed in the console: {IntranetURL} blocked a frame with origin {webCalURL} from accessing a cross-origin frame.

Upon regressing to v1.3.0 the iframe properly displays the calendar again.

**Comment by craigk5n** [comment]
Can you the Chrome developer tools to inspect the HTTP response header?  I'm curious if it is sending the correct headers.

**Comment by Tharrington86** [comment]
![Screenshot 2023-09-18 161952](https://github.com/craigk5n/webcalendar/assets/75510358/c253a785-c8f0-47fc-b26d-6912c1dc4ead)
![Screenshot 2023-09-18 162153](https://github.com/craigk5n/webcalendar/assets/75510358/467692ff-689e-4f47-837e-7db5b7610abc)
![Screenshot 2023-09-18 162227](https://github.com/craigk5n/webcalendar/assets/75510358/373492f1-eafe-47f3-a6c8-021730817747)

**Comment by craigk5n** [comment]
Forgot about that bit of code...  Hopefully latest commit will fix this: 5e5d0e5a70a590f5809530dcbf9735bbdfa9500a

**Comment by Tharrington86** [comment]
I can confirm that this change does work. I made the modifications and the calendar is now working in an iframe. Thank you!
