### ISSUE TITLE
[BUG] Timed event dropdown not functioning correctly

### ISSUE THREAD

**Issue by Tharrington86** [craigk5n/webcalendar#384]
Running version 1.3.0 and started to experience a weird bug. I have the calendar embedded in an iframe so that other employees can add meeting events to the calendar from our intranet home page. The calendar has been running flawless for quite some time. 

Now when you try to add a new event to the calendar and click on the dropdown to make the event "timed", there is a console error that pops up and then it takes about 30 seconds for the time picker to appear. 

js_cacher.php?inc=js/edit_entry.php/false/:131 Uncaught ReferenceError: form is not defined
    at timetype_handler (js_cacher.php?inc=js/edit_entry.php/false/:131:3)
    at HTMLSelectElement.onchange (edit_entry.php?date=20230815&defusers=:288:71)
timetype_handler @ js_cacher.php?inc=js/edit_entry.php/false/:131
onchange @ edit_entry.php?date=20230815&defusers=:288

After the time picker appears, the event can be added and saved as normal. I thought the iframe could be the culprit so I navigated directly to the URL and the same behavior is observed. 

As a last ditch effort I upgraded to v1.9.1 and the issue remains (with the added bug that iframes no longer can display the calendar. I created a separate issue for that).

**Comment by Tharrington86** [comment]
I have determined that this issue is present when the setting "Allow HTML content in event descriptions" is selected.

**Comment by craigk5n** [comment]
I just tried this with 1.9.7 with HTML content enabled and did not see this error.

**Comment by Tharrington86** [comment]
@craigk5n I'm sorry I did not specify the version we are using. We are using 1.3.0 because we need the webcalendar to be embedded in an iframe.

**Comment by Tharrington86** [comment]
Resolved after running upgrade.
