### ISSUE TITLE
Cannot export entries 

### ISSUE THREAD

**Issue by AxelDuerrbaum** [craigk5n/webcalendar#391]
Hello,

the export of entries always fails with the error message

WebCalendar Error
Fatal Error: Invalid form request

The variable $_REQUEST['csrf_form_key'] is empty, so preventHacking()  fails.

Used version of Webcalendar is v1.9.1-82-g9b7b3a55 
OS: Debian 11.7  with PHP 7.4.33

#0 preventHacking(em, ) called at [/opt/WWW/webcalendar/includes/formvars.php:175] #1 getGetValue(em) 
called at [/opt/WWW/webcalendar/includes/classes/WebCalendar.php:717] #2 WebCalendar->_initConnect() 
called at [/opt/WWW/webcalendar/includes/classes/WebCalendar.php:979] #3 WebCalendar->_doInit(2) 
called at [/opt/WWW/webcalendar/includes/classes/WebCalendar.php:1002] #4 WebCalendar->initializeSecondPhase() 
called at [/opt/WWW/webcalendar/includes/init.php:72] #5 include_once(/opt/WWW/webcalendar/includes/init.php) 
called at [/opt/WWW/webcalendar/export_handler.php:15]

**Comment by craigk5n** [comment]
Hopefully fixed with the commit shown here.

**Comment by AlbaVore** [comment]
Can you clarify if this was resolved at all? As its been marked as complete I assume that there was a resolution as I am still having the issue when attempting to export the calendar data.

**Comment by craigk5n** [comment]
I just tested this on the latest code in the main branch, and it works without issue.  Are you still having the issue with the latest code in git?  Or is this from one of the releases?

**Comment by AlbaVore** [comment]
Thanks for your message. The calendar is working as it should be.
I am using [WebCalendar v1.9.1 ((08 Mar 2022))) Is that the latest release?

 I want to export all the entries so that I can then import a new file of data.

**Comment by craigk5n** [comment]
That is the latest release, but there is a fix in the git repo (not yet part of a release).  I'll try to get a release out soon, but it needs some testing on the install/upgrade first.

**Comment by craigk5n** [comment]
In the mean time, you could just update the export.php file from what is in the git repo to get it working.

**Comment by AlbaVore** [comment]
Thanks Craig, I have swapped out the export.php for the newer one. This does allow an export in three formats but the csv version appears to return a file with an error message  within rather than data. 
The newer export.php does not appear to offer the same option to select specific date range for export of data.
Its a bit of progress so for that I am grateful.

**Comment by AlbaVore** [comment]
Also meant to ask if the latest release is still not functioning under php8?
