### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by felipek9** [craigk5n/webcalendar#4]
Can you please guide me on how I can fix my characters view?
Can't read those words ç/á/é/í/ó/ú/ã/õ/à/è/ì/ò/ù

**Comment by jbyvosges** [comment]
Chose encoding UTF8

**Comment by felipek9** [comment]
In what file can I chose?

**Comment by jbyvosges** [comment]
In what context ? I would say you have to choose UTF8 in the browser.

**Comment by felipek9** [comment]
Just found out, thanks!
