### ISSUE TITLE
Undefined vars in edit_entry.php

### ISSUE THREAD

**Issue by irb** [craigk5n/webcalendar#40]
In git master, when accessing edit_entry.php, the site complains of use_fckedit and use_htmlarea being undefined. I've tried with and without includes/FCKeditor-2.0 being present. 

At the top of the page, under Add Entry (event): 
```
Notice: Undefined variable: use_fckeditor in <path>/webcalendar-git/edit_entry.php on line 612
Notice: Undefined variable: use_htmlarea in <path>/webcalendar-git/edit_entry.php on line 612
```
And then, just above the Save button,

`
Notice: Undefined variable: use_fckeditor in <path>/webcalendar-git/edit_entry.php on line 1693
`

Needless to say hitting the save button does nothing.

**Comment by craigk5n** [comment]
Could not reproduce in my environment, but hopefully fixed in commit mentioned above.
