### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by afoster1955** [craigk5n/webcalendar#402]
I keep getting the following error message when trying to get the install process going.  Where is this directory supposed to be set up?

Failure ReasonDatabase Cache Directory does not exist

The installation wizard has it listed as /tmp

**Comment by craigk5n** [comment]
Try leaving the cache dir blank.  I haven't seen that error, but /tmp should exist on almost all Linux systems.

**Comment by afoster1955** [comment]
If I leave the cache dir blank, I get to the page that says that there is an upgrade to the mysql but then it never lets me move on to the next screen.  I am trying this on a localhost on my laptop which may be the reason there is no /tmp directory.
