### ISSUE TITLE
Installing webcalendar-master on XAMPP, but does not accept database type

### ISSUE THREAD

**Issue by barrykirk** [craigk5n/webcalendar#437]
Hi, 

I am trying to install webcalendar-master on to my XAMPP instance, but do not know how to resolve and error,

With incorrcet DB Type.

Can anyone please help/advise?

Settings storage: includes/settings.php
Database connection: Cannot connect: dbi_error(): db_type not defined.
Number of admin users: 0
WebCalendar version (installer): v1.9.12
WebCalendar version (database):
Warning: Undefined variable $detectedDbVersion in C:\xampp\htdocs\webcalendar-master\install\index.php on line 444

PHP version: Supported (8.2.0)

**Comment by craigk5n** [comment]
I've made some fixes to the installer.  Try the latest code in the master branch again.  Please re-open if you are still having issues.
