### ISSUE TITLE
Error executing query. Mysqli

### ISSUE THREAD

**Issue by Szirenke** [craigk5n/webcalendar#466]
Dear All, 

I am trying to configure the database for web calendar (v1.9.12) and I run into the error of "Error executing query." I am using an almalinux 9 box with php 8.3.3 and I already uncommented the extension=mysqli line in the php.ini file. It says it can connect but somehow it cannot execute the mysql script. Is there something I forgot? mysql is running I can run mysql from the terminal and everything is stored in /var/lib. What is the trick here? Setting the mode to dev Gives this error: 

"Table 'xycalendar.webcal_config' doesn't exist." How does one create this? 

I am also wondering which file path is it asked for when I switch to SQlite3 database. I create the database and give the file path tot he database but it says it cannot connect. Which file path is it? 

Thanks!

**Comment by Szirenke** [comment]
Hi,

I now tried with web calendar 1.9.10 and I am also following the actions in phpmyadmin. web calendar installation populates the database as it should but then it wants to upgrade which probably fails and does not allow to go to next page. It seems that the database is correctly created since it can be checked in phpmyadmin. What does it want to upgrade?

**Comment by Szirenke** [comment]
Hi,

I am now back to version v1.9.12 of webcalendar and after I get this error: 

Error executing query.

No database selected

 This error also stays when I create the tables in the mysql database in phpmyadmin. No matter what I do I cannot proceed from this step. Any suggestions?

**Comment by s22-tech** [comment]
The fix can be found in this issue:

https://github.com/craigk5n/webcalendar/issues/471

**Comment by Szirenke** [comment]
Many thanks for this! It works now!
