### ISSUE TITLE
Categories cannot be added even if it is enabled in settings

### ISSUE THREAD

**Issue by Szirenke** [craigk5n/webcalendar#487]
Hi, 

After the #471 fix webcalnder now is running however I cannot add categories even if it is enabled in settings together with icons. 

Is there hard coded setting for this in a .php file I could flip?

**Comment by mada0068** [comment]
I have had the same problem. I have detected that the last change for postgress compatibility has broken the mysql process. I have changed the line 73 to the previous version (changing '' by "") and it works

**Comment by Szirenke** [comment]
Hi, thanks. which file have you modified at line 73?

**Comment by Szirenke** [comment]
Sorry, I see now. I edited the category_handler.php and it works now! 

Thanks a lot!

**Comment by Szirenke** [comment]
Hi again right now it seems that I can add a category but it is not used when making a booking and it does not display anything when I sort it as a new category.

**Comment by craigk5n** [comment]
I just made two changes to help with categories. Hopefully, this is fixed now.  If not, please reopen this issue.
