### ISSUE TITLE
Error when creating a new category

### ISSUE THREAD

**Issue by s22-tech** [craigk5n/webcalendar#496]
`PHP Parse error: syntax error, unexpected single-quoted string " )" in /cal/category_handler.php on line 74`

I fixed it by making this change:

```
if (!dbi_execute("
   DELETE FROM `webcal_entry_categories`
   WHERE `cat_id` = ? AND ( `cat_owner` = ?"
    . ($is_admin ? " OR `cat_owner` = '' )" : " )"),
   [$id, $login]
)) {
```
Switching to double quotes around the SQL not only eliminates the problem, but also makes the SQL stand out from the rest of the code.

**Comment by s22-tech** [comment]
Unfortunately, I'm not able to delete a category.  I'm not getting an error, but 
`$delete = getPostValue('delete');`
appears to be empty.

**Comment by s22-tech** [comment]
I'm getting this error in the console.  It flashes briefly before disappearing, so I had to take a video of it, and then a still.  There is no line 238 in category.php, let alone a line 170, so not sure what it's referring to.

![Screenshot 2024-06-25 at 8 43 11 PM](https://github.com/craigk5n/webcalendar/assets/59073912/f2393305-f917-4a55-a2a9-3506ae269634)

**Comment by s22-tech** [comment]
I found it.  Line 89 of category.php is missing a quote mark.  Change this:

`. 'type="submit" onclick="return confirm('`

to this:

`. 'type="submit" onclick="return confirm(\''`

**Comment by craigk5n** [comment]
Should be fixed now.
