### ISSUE TITLE
About page has wrong date. 28 Sep 2008

### ISSUE THREAD

**Issue by htukiain** [craigk5n/webcalendar#50]
In 1.3 about page has a date 28 sept 2008.
Should be someting  in August 2017 or even later.

--------------------
WebCalendar

version v1.3.0
**28 Sep 2008**

WebCalendar is a PHP application used to maintain a calendar for a single user or an internet / intranet group of users. It can also be configured as an event calendar.

**Comment by craigk5n** [comment]
Fixed in 1.9.1
