### ISSUE TITLE
Categories cannot be added to entry

### ISSUE THREAD

**Issue by Szirenke** [craigk5n/webcalendar#507]
Hi, 

When adding a new entry to the calendar the categories cannot be added. One can choose a category but it will not be added to the entry. The categories are allowed in the settings. How could I make the categories appear in the new entry?

Thanks!

**Comment by craigk5n** [comment]
Should be fixed in latest commit

**Comment by Szirenke** [comment]
Thank you so much!! It is working now beautifully.
