### ISSUE TITLE
Error in ADMIN.php

### ISSUE THREAD

**Issue by Jbekker63** [craigk5n/webcalendar#54]
In admin PHP when I change the Email settings it looks lik it's not working.
also toggle SMTP settings are vissible when PHP-m,ail is selected

ALso there are some floating " (double quotes) 

![image](https://user-images.githubusercontent.com/32453839/31288731-7163856e-aac6-11e7-9138-f0a33b1373ab.png)

**Comment by craigk5n** [comment]
Fix included in commit d31482f
