### ISSUE TITLE
Remote calendar import requires php7.0-xml (SOLVED)

### ISSUE THREAD

**Issue by rasos** [craigk5n/webcalendar#56]
`[Wed Nov 08 20:48:12.361140 2017] [:error] [pid 28430] [client 10.81.228.23:49952] PHP Fatal error:  Uncaught Error: Call to undefined function utf8_decode() in /var/www/html/calendar.fair.domain/public_html/WebCalendar-1.2.9/includes/xcal.php:2507\nStack trace:\n#0 /var/www/html/calendar.fair.coop/public_html/WebCalendar-1.2.9/includes/xcal.php(2134): format_ical(Array)\n#1 /var/www/html/calendar.fair.coop/public_html/WebCalendar-1.2.9/edit_remotes_handler.php(116): parse_ical('https://fairkom...', 'remoteics')\n#2 {main}\n  thrown in /var/www/html/calendar.fair.domain/public_html/WebCalendar-1.2.9/includes/xcal.php on line 2507, referer: http://calendar.fair.domain/edit_remotes.php?add=1`

mysql  Ver 14.14 Distrib 5.7.20    
PHP 7.0.22-0ubuntu0.16.04.1

You need to add php xml extensions, they are no longer available in standard php7:   
`sudo apt-get install php7.0-xml`

**Comment by craigk5n** [comment]
As of PHP 7.2, this function is now part of the PHP core.

https://www.php.net/manual/en/function.utf8-decode.php
