### ISSUE TITLE
Patches from the sourceforge repo

### ISSUE THREAD

**Issue by monnerat** [craigk5n/webcalendar#6]
Hi Craig,

As the Fedora packager of WebCalendar, I left some patches a long time ago on the SF repo: these were never merged nor rejected:
- https://sourceforge.net/p/webcalendar/bugs/2437/
- https://sourceforge.net/p/webcalendar/patches/594/
- https://sourceforge.net/p/webcalendar/patches/591/
- https://sourceforge.net/p/webcalendar/patches/593/
- https://sourceforge.net/p/webcalendar/patches/596/ (to be applied after 594)

If you are interested in merging them, I can create a PR for you.

Thanks for your reply,
Patrick

**Comment by craigk5n** [comment]
Yes, I would be interested in seeing these patches as pull requests.

Thanks,
Craig

**Comment by monnerat** [comment]
I started the merges, but there is a problem with https://sourceforge.net/p/webcalendar/patches/591/ because the user enable/disable feature is only partially removed.
Are you OK to remove it completely ? Thanks for the reply.

**Comment by monnerat** [comment]
Pull request #12 complete. Closing issue.
