### ISSUE TITLE
Foreign characters prevent entry description from displaying when English is the calendar language.

### ISSUE THREAD

**Issue by Flancandrin** [craigk5n/webcalendar#65]
Try an ñ to confirm.  I may have fixed this by changing the character encoding to UTF-8 in the English translation file, but I did a bunch of other things at once so not sure.

**Comment by FranzGotsis** [comment]
UTF-8 in the English translations file ***and*** the database (MySQL and MariaDB 5 and 10) did resolve the issue for me.

**Comment by Flancandrin** [comment]
> UTF-8 in the English translations file _**and**_ the database (MySQL and MariaDB 5 and 10) did resolve the issue for me.

Where did you make the change in the database?

**Comment by mnovoa** [comment]
Hi, Where did you change ?, I have the same problem.
Thank you

**Comment by FranzGotsis** [comment]
Just log into the database with PHPMyAdmin that is used by WebCalendar. Then change all table fields to UTF-8 ("Alter Table" - command). Best is to dump the contents of the database first and to freeze it until the change is done. The means preventing people using the WebCalendar to make changes while you are modifying the database.

The translation files are stored on the server in the directory translations just below the root directory of WebCalendar.
