### ISSUE TITLE
replace some for loops with str_repeat()

### ISSUE THREAD

**Issue by bbannon** [craigk5n/webcalendar#7]
I haven't looked at WebCalendar for months but, I suddenly have some time.
What do you think of this patch to replace some for loops with str_repeat()? 
[loop2strrepeat.zip](https://github.com/craigk5n/webcalendar/files/1185199/loop2strrepeat.zip)

**Comment by craigk5n** [comment]
Hey there Bruce.

Can you generate a pull request for this?

**Comment by nohjwhh1** [comment]
I don't know. I only just signed up with github. Don't know all the 
ins/outs yet.

**Comment by craigk5n** [comment]
Which version of the code is the patch for?

**Comment by craigk5n** [comment]
Code is in master branch now.  Thanks, Bruce.

**Comment by bbannon** [comment]
It's for the current webcalendar master on github.

I'm guessing that this message is from before I figured out the pull 
request thing?

Bruce
