### ISSUE TITLE
User manager - cannot switch to Group Tab 

### ISSUE THREAD

**Issue by martinbohuslav** [craigk5n/webcalendar#76]
Hello,
if you want to add group, you have to go to User Manager Settings. There is several tabs (depending what you have seleceted in preferences). If you click on Group tab, nothing happens.

There is an error in \includes\js\users.php 
missing commas

right code:
var tabs =  ['','users','groups','nonusers','remotes'];

**Comment by FranzGotsis** [comment]
Hello 
I am running WebCalendar 1.2.9 with the changes I added to correct some issues (see https://github.com/craigk5n/webcalendar/pull/77)

Adding user groups works with my setup.

The current code in includes\js\users.php in my installation is:
var tabs = new Array ();
tabs[1] = "users";
tabs[2] = "groups";
tabs[3] = "nonusers";
tabs[4] = "remotes";

kind regards
Franz

**Comment by martinbohuslav** [comment]
my version where is reported this issue: WebCalendar v1.3.0 ((from git repo))

**Comment by craigk5n** [comment]
Fixed with commit 55995c65e61692cc73164e34330aa91f186e74f1
