### ISSUE TITLE
Title, Description, Location etc NOT SHOWING unless logged in.

### ISSUE THREAD

**Issue by KE0KEY** [craigk5n/webcalendar#78]
Everytime an entry is made the Title, Description, Location etc information only appears when someone is logged in. Everything is set to Public as far as I can tell. Here are a couple of examples of how things are appearing:

1. On the calendar Month View this is what appears in the window for that day:
     06:00 - 09:00» Not available
     08:00 - 11:00» Not available
     21:00 - 00:00» Not available

2. When you click on an event to view it, this is how it appears:
     
Description: | Not available
Location: | Not available
URL: | Not available
Date: | Sunday, February 25, 2018
Repeat Type: | Daily
Time: | 06:00-09:00 EST
Duration: | 3 hours
Access: | Public
Category: | ECHOLINK NET*
Created by: | DEFAULT ADMINISTRATOR
Updated: | Saturday, February 24, 2018 17:48 GMT
Comments: | None

Please let me know what I am doing wrong or how this can be corrected. If you need to view my calendar you can by visiting http://www.NetSchedule.Info 

Thank You
James

**Comment by craigk5n** [comment]
Hmmm.... looks like it is working now.  Did you get this resolved?

**Comment by KE0KEY** [comment]
Yes, I did, thank you...


James Pfeifer (KE0KEY)
ke0key@hotmail.com
www.GlobalDX.net<http://www.GlobalDX.net>
(Founder)
________________________________
