### ISSUE TITLE
Database Type: please can you help me change for mysql default is sqlite3,thanks!!

### ISSUE THREAD

**Issue by wenchangming211** [craigk5n/webcalendar#83]

**Comment by wenchangming211** [comment]
没有中文的安装部署文档吗，这个安装过程太麻烦！！

**Comment by bbannon** [comment]
If your PHP installation has the database enabled, you should be able to select it when you run the install wizard.

**Comment by craigk5n** [comment]
No reply to bbannon's comment, so I"m assuming this was resolved.
