### ISSUE TITLE
[Question] How to improve security?

### ISSUE THREAD

**Issue by s33d3r** [craigk5n/webcalendar#91]
What should be the optimal files and folder permissions to improve security?
What's needed in order to deny files reads/writes that aren't needed for WebCalendar to run?
Current setup: www-data owns the whole folder, and the permissions are the default except for includes folder, for which I've denied write permission. I've also removed Indexes in apache2.conf to disable directory listing.
Thanks!

**Comment by craigk5n** [comment]
There is a built-in report that will show what the best permissions settings are and whether your installation meets those suggestions.  Go to "Reports" and then "Security Audit".
