### ISSUE TITLE
In 1.2.9 is not possible to continue using sqlite3

### ISSUE THREAD

**Issue by Pitriss** [craigk5n/webcalendar#97]
I tried to upgrade to 1.2.9 from some legacy version but unfortunatelly i can't do that.. On my sserver is php 7.0 installed and sqlite3 is enabled in php although I can't select it.

It was running fine on old version, so why was support dropped? On my debian stretch (on ARM if that does matter) I have no other DB installed and i don't plan to do so.

Could you please add support for sqlite3 back? Other apps works with sqlite3 just fine on my instalation.

**Comment by craigk5n** [comment]
SQLite3 is supported... not sure why you wouldn't be seeing it.  You can see in the docker version, we are using PHP 7.1 with SQLite:

https://github.com/craigk5n/webcalendar-docker
