### ISSUE TITLE
Global categories only visible for administrative users

### ISSUE THREAD

**Issue by mimph** [craigk5n/webcalendar#98]
I'm setting up a calendar application using webcalendar 1.3.0 and I just noticed that I don't see global categories as a regular user.

Calendar users without administrative rights can only see the categories created by themselves. This is a problem, because you might want to have multiple non-admin users with the ability to create content and sort them into the same (global) categories. Every user can sort his own content into his own categories, but these categories are only accessible by that single user (not even by an administrator). Global categories would be especially important, if you want to manage a shared calendar with multiple users (such as the public access calendar).

Global categories are only accessible by administrative users. This is better than nothing, but I wouldn't like to give every user administrative rights in order to allow them the use of global categories.

**Comment by craigk5n** [comment]
Fixed with commit c4e92c813cc4b045cdfd343f27c524a9762cb01d
